// GENERATED FILE — DO NOT MODIFY BY HAND
// Generated by `dart run assets/sounds/generator.dart` command in ReSpire directory.
// Remember about correct filename, - and _ are changed to space, first letter is capitalized.

import 'package:respire/components/Global/SoundAsset.dart';

class ReSpireSounds {
  final Map<String, SoundAsset> longSounds = {
    "Ainsa": SoundAsset(name: "Ainsa", path: "sounds/long/Ainsa.mp3", type: SoundType.melody),
    "Binaural Meditation": SoundAsset(name: "Binaural Meditation", path: "sounds/long/Binaural-Meditation.mp3", type: SoundType.melody),
    "Birds": SoundAsset(name: "Birds", path: "sounds/long/Birds.mp3", type: SoundType.melody),
    "Chanting 1": SoundAsset(name: "Chanting 1", path: "sounds/long/Chanting-1.mp3", type: SoundType.melody),
    "Chanting 2": SoundAsset(name: "Chanting 2", path: "sounds/long/Chanting-2.mp3", type: SoundType.melody),
    "Cinematic Ambient": SoundAsset(name: "Cinematic Ambient", path: "sounds/long/Cinematic-Ambient.mp3", type: SoundType.melody),
    "Dark space": SoundAsset(name: "Dark space", path: "sounds/long/Dark-space.mp3", type: SoundType.melody),
    "Fireplace": SoundAsset(name: "Fireplace", path: "sounds/long/Fireplace.mp3", type: SoundType.melody),
    "Low hz": SoundAsset(name: "Low hz", path: "sounds/long/Low-hz.mp3", type: SoundType.melody),
    "Ocean": SoundAsset(name: "Ocean", path: "sounds/long/Ocean.mp3", type: SoundType.melody),
    "Odliczanie   Copy": SoundAsset(name: "Odliczanie   Copy", path: "sounds/long/odliczanie - Copy.mp3", type: SoundType.melody),
    "Odliczanie wstecz": SoundAsset(name: "Odliczanie wstecz", path: "sounds/long/Odliczanie-wstecz.mp3", type: SoundType.melody),
    "Odliczanie": SoundAsset(name: "Odliczanie", path: "sounds/long/odliczanie.mp3", type: SoundType.melody),
    "Rain": SoundAsset(name: "Rain", path: "sounds/long/Rain.mp3", type: SoundType.melody),
    "Relaxing sounds": SoundAsset(name: "Relaxing sounds", path: "sounds/long/Relaxing-sounds.mp3", type: SoundType.melody),
    "Solfeggio Frequency": SoundAsset(name: "Solfeggio Frequency", path: "sounds/long/Solfeggio-Frequency.mp3", type: SoundType.melody),
    "Theta": SoundAsset(name: "Theta", path: "sounds/long/Theta.mp3", type: SoundType.melody),
  };

  final Map<String, SoundAsset> shortSounds = {
    "Beep": SoundAsset(name: "Beep", path: "sounds/short/Beep.mp3", type: SoundType.cue),
    "Bell": SoundAsset(name: "Bell", path: "sounds/short/Bell.mp3", type: SoundType.cue),
    "Harp": SoundAsset(name: "Harp", path: "sounds/short/Harp.mp3", type: SoundType.cue),
    "Pop": SoundAsset(name: "Pop", path: "sounds/short/Pop.mp3", type: SoundType.cue),
    "Snap": SoundAsset(name: "Snap", path: "sounds/short/Snap.mp3", type: SoundType.cue),
    "Wdech": SoundAsset(name: "Wdech", path: "sounds/short/Wdech.mp3", type: SoundType.cue),
    "Whistle Down": SoundAsset(name: "Whistle Down", path: "sounds/short/Whistle-Down.mp3", type: SoundType.cue),
    "Whistle Up": SoundAsset(name: "Whistle Up", path: "sounds/short/Whistle-Up.mp3", type: SoundType.cue),
    "Wstrzymanie": SoundAsset(name: "Wstrzymanie", path: "sounds/short/Wstrzymanie.mp3", type: SoundType.cue),
    "Wydech": SoundAsset(name: "Wydech", path: "sounds/short/Wydech.mp3", type: SoundType.cue),
    "Zatrzymanie": SoundAsset(name: "Zatrzymanie", path: "sounds/short/Zatrzymanie.mp3", type: SoundType.cue),
    "Zen gong": SoundAsset(name: "Zen gong", path: "sounds/short/Zen-gong.mp3", type: SoundType.cue),
  };

  final Map<String, SoundAsset> countingSounds = {
    "Clock": SoundAsset(name: "Clock", path: "sounds/counting/Clock.mp3", type: SoundType.counting),
    "Metronome": SoundAsset(name: "Metronome", path: "sounds/counting/Metronome.mp3", type: SoundType.counting),
  };
}
