import 'dart:ffi';
import 'dart:io';
import 'package:respire/utils/TextUtils.dart';

// To use generator run `dart run assets/sounds/generator.dart` command in ReSpire directory.
// Remember about correct filename, - and _ are changed to space, first letter is capitalized.

class SoundsInfo {
  final String soundType;
  final String directory;
  final String mapName;

  SoundsInfo({
    required this.soundType,
    required this.directory,
    required this.mapName,
  });
}

List<String> mapFiles (Directory directory){
    return directory
        .listSync()
        .whereType<File>()
        .where((f) => f.path.endsWith('.mp3'))
        .map((f) => f.uri.pathSegments.last.replaceAll('.mp3', ''))
        .toList();
  }

void main() async {
  SoundsInfo longSounds = SoundsInfo(
    soundType: 'melody',
    directory: 'long',
    mapName: 'longSounds',
  );
  SoundsInfo shortSounds = SoundsInfo(
    soundType: 'cue',
    directory: 'short',
    mapName: 'shortSounds',
  );
  SoundsInfo countingSounds = SoundsInfo(
    soundType: 'counting',
    directory: 'counting',
    mapName: 'countingSounds',
  );
  final soundsList = [longSounds, shortSounds, countingSounds];

  final String path = './assets/sounds/';
  final longFiles = mapFiles(Directory('$path${longSounds.directory}'));
  final shortFiles = mapFiles(Directory('$path${shortSounds.directory}'));    
  final countingFiles = mapFiles(Directory('$path${countingSounds.directory}'));
  final filesList = [longFiles, shortFiles, countingFiles];

  final buffer = StringBuffer()
    ..writeln('// GENERATED FILE — DO NOT MODIFY BY HAND')
    ..writeln('// Generated by `dart run assets/sounds/generator.dart` command in ReSpire directory.')
    ..writeln('// Remember about correct filename, - and _ are changed to space, first letter is capitalized.\n')
    ..writeln("import 'package:respire/components/Global/SoundAsset.dart';\n")
    ..writeln('class ReSpireSounds {');

    
  for (int i = 0; i < soundsList.length; i++) {
    final sounds = soundsList[i];

    buffer.writeln('  final Map<String, SoundAsset> ${sounds.mapName} = {');
    for (var name in filesList[i]) {
      final displayName = TextUtils.capitalizeAndRemoveTextSeparators(name);
      buffer.writeln(
          '    "$displayName": SoundAsset(name: "$displayName", path: "sounds/${sounds.directory}/$name.mp3", type: SoundType.${sounds.soundType}),');
    }

    if(i!=soundsList.length - 1) {
      buffer.writeln('  };\n');
    }
    else {
      buffer.writeln('  };');
      buffer.writeln('}');
    }
  }

  final outFile = File('./lib/components/Global/Sounds_lists.g.dart');
  outFile.writeAsStringSync(buffer.toString());

  print('Generated Sounds_lists.g.dart with ${longFiles.length + shortFiles.length + countingFiles.length} entries.');
}