import 'dart:io';
import 'package:respire/utils/TextUtils.dart';

void main() async {
  final longDir = Directory('./assets/sounds/long');
  final countingDir = Directory('./assets/sounds/counting');
  final shortDir = Directory('./assets/sounds/short');

  final longFiles = longDir
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.mp3'))
      .map((f) => f.uri.pathSegments.last.replaceAll('.mp3', ''))
      .toList();

  final shortFiles = shortDir
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.mp3'))
      .map((f) => f.uri.pathSegments.last.replaceAll('.mp3', ''))
      .toList();

  final countingFiles = countingDir
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.mp3'))
      .map((f) => f.uri.pathSegments.last.replaceAll('.mp3', ''))
      .toList();

  final buffer = StringBuffer()
    ..writeln('// GENERATED FILE — DO NOT MODIFY BY HAND')
    ..writeln('// Generated by `dart run assets/sounds/generator.dart` command in ReSpire directory.')
    ..writeln('// Remember about correct filename, - and _ are changed to space, first letter is capitalized.\n')
    ..writeln("import 'package:respire/components/Global/SoundAsset.dart';\n")
    ..writeln('class ReSpireSounds {')
    ..writeln('  final Map<String, SoundAsset> longSounds = {');

  for (var name in longFiles) {
    final displayName = TextUtils.capitalizeAndRemoveTextSeparators(name);
    buffer.writeln(
        '    "$displayName": SoundAsset(name: "$displayName", path: "sounds/long/$name.mp3", type: SoundType.melody),');
  }

  buffer.writeln('  };\n');
  buffer.writeln('  final Map<String, SoundAsset> shortSounds = {');

  for (var name in shortFiles) {
    final displayName = TextUtils.capitalizeAndRemoveTextSeparators(name);
    buffer.writeln(
        '    "$displayName": SoundAsset(name: "$displayName", path: "sounds/short/$name.mp3", type: SoundType.cue),');
  }
  
  buffer.writeln('  };\n');
  buffer.writeln('  final Map<String, SoundAsset> countingSounds = {');

  for (var name in countingFiles) {
    final displayName = TextUtils.capitalizeAndRemoveTextSeparators(name);
    buffer.writeln(
        '    "$displayName": SoundAsset(name: "$displayName", path: "sounds/counting/$name.mp3", type: SoundType.counting),');
  }

  buffer.writeln('  };');
  buffer.writeln('}');

  final outFile = File('./lib/components/Global/Sounds_lists.g.dart');
  outFile.writeAsStringSync(buffer.toString());

  print('Generated Sounds_lists.g.dart with ${longFiles.length + shortFiles.length} entries.');
}
